# Generated by Django 4.0 on 2021-12-30 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fuel', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('hybrid', 'Hybrid'), ('gas', 'Gas')], max_length=10)),
            ],
        ),
    ]
