# Generated by Django 4.0 on 2022-01-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_auth', '0002_remove_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
