# Generated by Django 4.0 on 2022-01-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_auth', '0003_alter_profile_age_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
